version: '2'

services:
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      # - ./dist-2.0/ui:/app
      - ./dist-1.2:/app
      - ./cyclos-ui_vhost.conf:/vhosts/my_vhost.conf:ro